databases:
  - name: postgres
    databaseName: people_pages
    user: people_pages
    ipAllowList: []
    region: ohio

services:
  - type: web
    name: people_pages
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
    region: ohio